// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi7UAyz_9BEhtHmkcmXHAUQJPFcgNgvHA',
    appId: '1:133421342974:ios:f433763ed797f9f64c85af',
    messagingSenderId: '133421342974',
    projectId: 'cinemas-app-24539',
    databaseURL: 'https://cinemas-app-24539-default-rtdb.firebaseio.com',
    storageBucket: 'cinemas-app-24539.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi7UAyz_9BEhtHmkcmXHAUQJPFcgNgvHA',
    appId: '1:133421342974:ios:f433763ed797f9f64c85af',
    messagingSenderId: '133421342974',
    projectId: 'cinemas-app-24539',
    databaseURL: 'https://cinemas-app-24539-default-rtdb.firebaseio.com',
    storageBucket: 'cinemas-app-24539.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDSOu_gDjKXHohJkUzrpngvVlGF-B6MEc',
    appId: '1:133421342974:web:723033e9f8e6ba2c4c85af',
    messagingSenderId: '133421342974',
    projectId: 'cinemas-app-24539',
    authDomain: 'cinemas-app-24539.firebaseapp.com',
    databaseURL: 'https://cinemas-app-24539-default-rtdb.firebaseio.com',
    storageBucket: 'cinemas-app-24539.firebasestorage.app',
    measurementId: 'G-VNXRYFDPYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMDtBMwSr-awWO-YIZe0ulQIDZMfbgag',
    appId: '1:133421342974:android:ce843ccff25ff6f74c85af',
    messagingSenderId: '133421342974',
    projectId: 'cinemas-app-24539',
    databaseURL: 'https://cinemas-app-24539-default-rtdb.firebaseio.com',
    storageBucket: 'cinemas-app-24539.firebasestorage.app',
  );

}